### ISSUE TITLE
More transparent energy machanics for LC

### ISSUE THREAD

**Issue by GvardianDLVII** [InsideEarth2150/IEO-Updates#11]
It is hard to understand the LC energy system, with solar power plants, panels, batteries, Xyrex, etc. 

I would like to see aggregated battery level of all my batteries, when I select one. Displayed consumption is also slightly inaccurate, since during daytime it shows the total production (as everything that is more than needed goes to the batteries).

An option could be to display estimated remaining time until discharging batteries, when  I select one, and the batteries are discharging.

**Comment by nutzeeer** [comment]
I would also like the option to replace the total energy output with a number that is negative or positive, depending on whether the batteries are being discharged or not. a large negative number being faster discharge.

**Comment by GvardianDLVII** [comment]
Implemented and released in EarthExtensions v1.26
