### ISSUE TITLE
Mouse movement fix

### ISSUE THREAD

**Issue by S0m3Th1nG-AwFul** [InsideEarth2150/IEO-Updates#22]
Will the new patch contain mouse movement bugfix, like in known `Earth 2150 Mix Sets by Junior_Djjr`?

`FixMouseMovement  = 1       # (0|1) fix mouse movement bugs. You'll hardly deactivate it.`

**Comment by Animal-UK** [comment]
It is the desire of IEO to consolidate all bug/fixes into a unified patch, however without the source knowledge/code this fix it will take some time complete.

**Comment by Animal-UK** [comment]
$offset = 0x2845D6
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset++] = 0x90
$bytes[$offset] = 0x90

Credit:  jmp64
