### ISSUE TITLE
Differentiate construction vehicle maxHP

### ISSUE THREAD

**Issue by Skeltek** [InsideEarth2150/IEO-Updates#24]
**Is your feature request related to a problem? Please describe.**
Currenlty, there is no possibility of a unit script to determine what unit type it is used by.

**Describe the solution you'd like**
If units had a differing amount of maxHP, the script could check the units maxHP in order to determine what unit it is used by.

**Describe alternatives you've considered**
No alternative solutions could be found. Even if it was possible to determine the players faction, construction vehicles can be transfered and break the solution.

**Additional context**
ED construction vehicles having slightly more HP would as well be good for balancing, since ED is much more dependant on construction vehicles especially at the beginning of the game. UCS can afford spending money on redundant/surplus amount of spares.
Similar techniques/workarounds were pretty common and standard in game development. Color-selection for determining objects clicked on with a mouse button also used tertiary vectors to determine a required variable.

**Comment by GvardianDLVII** [comment]
The feature is currently not needed afaik. I would be more into actually extending scripting capabilities of EarthC rather than relying on max HP of unit, but the topic could be approached again if the need for it shows up.
