### ISSUE TITLE
LC Upg.Mine keybind

### ISSUE THREAD

**Issue by GvardianDLVII** [InsideEarth2150/IEO-Updates#32]
You cannot bind upg. mine to any key. There is a feature request for extending keybinds, but this one is slightly different. Game should use the same keybind for both standard and upgraded mine, placing the better one if it is available. I have already developed a solution to that problem, so it only needs to be accepted to be included in future releases.

**Comment by Animal-UK** [comment]
you'll need to share the solution for review 😂 @GvardianDLVII

**Comment by GvardianDLVII** [comment]
Released in EarthExtensions v1.0.20, along with a similar Xyrex keybind
