### ISSUE TITLE
Submarines & Nukes

### ISSUE THREAD

**Issue by AlphaOmega2020** [InsideEarth2150/IEO-Updates#4]
**Describe the bug**
When you fire a nuke from a sub, you can hear the launch but there is no rocket or target impact

**To Reproduce**
Steps to reproduce the behaviour:
1. research submarines and nukes
2. target & fire

**Expected behaviour**
A nuke can be seen launching and impacts its target, unless intercepted by SDI.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H0
 - Game + Version: TMP/LS. 2.2

**Comment by Animal-UK** [comment]
Broken since 2.1

**Comment by Animal-UK** [comment]
Looks to resolved by extracting the Update22.wd container and then re-creating it

**Comment by Animal-UK** [comment]
Cannons

EDWSHR1 > fireType > #halfFire > #singleFire
EDWSHR2 > fireType > #halfFire > #singleFire

UCSWSHR1 > fireType > #halfFire > #singleFire
UCSWSHR2 > fireType > #halfFire > #singleFire

**Comment by nutzeeer** [comment]
Isnt this problem fixed and replaced by sub nukes not being intercepted by SDI?
