### ISSUE TITLE
SDI

### ISSUE THREAD

**Issue by AlphaOmega2020** [InsideEarth2150/IEO-Updates#5]
**Describe the bug**
ED & UCS SDI seems bugged, very rarely UCS SDI will work, ED SDI never seems to an LC SDI does seem to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. research SDI, have enemy shoot nukes next to SDI and you will see that it doesn't shot the Nukes down

**Expected behaviour**
SDI should shoot the nuke before it hits the ground.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Game + Version: TMP/LS. 2.2

**Comment by Animal-UK** [comment]
SDI is fixed by restoring original 1.3 values, however UCS MDW is not intercepted due to angle of fire, further investigation and testing required.

**Comment by Animal-UK** [comment]
SDI is fixed by restoring original 1.3 values, however UCS MDW is not intercepted due to angle of fire, further investigation and testing required.

**Comment by Animal-UK** [comment]
SDI is fixed by restoring original 1.3 values, however UCS MDW is not intercepted due to angle of fire, further investigation and testing required.

**Comment by Animal-UK** [comment]
Cannons: UCSCSD
neededResearches Empty > RES_UCS_WSD
maxAlphaPerTick 15 > 3
maxBetaPerTick 10 > 3
targetType #targetTypeAirOnly > #targetTypeGroundAndAir


Doesnt resolve long shots. TBC
