### ISSUE TITLE
Screen shaking option selection

### ISSUE THREAD

**Issue by koniecpolski** [InsideEarth2150/IEO-Updates#52]
I wish I could deselect visual effects like screen shaking while structure gets destroyed (especially UCS Power plant) and nukes fall down. It is disturbing and I can't properly aim my pointer. Like Ajack said: "Camera is floating in the air, so there should not be any vibrations around".

**Comment by nutzeeer** [comment]
Maybe it would be enough to tone it down severely? This way we could retain the impression of "shaking ground"

**Comment by Animal-UK** [comment]
both options are viable.. we can remove or tone it down.

I dont think an in game selection will be possible for a while or ever given its imbedded in the .par

**Comment by koniecpolski** [comment]
Only UCS power plant shaking off isn't enough for me. I play mainly LC and **my structures** exploding makes defending much harder - I can't point my indicator at the target near dying building. I hope I will be able to disable that _preposterous_ trembling for every structure, even if I order it to auto-destruct.

**Comment by GvardianDLVII** [comment]
You can check 1.0.14 release of EarthExtensions - I added an option to reduce the effect (or even remove it completely)

**Comment by koniecpolski** [comment]
Could it be used in multiplayer game? (with other players that don't have shaking disabled) 🤔

**Comment by GvardianDLVII** [comment]
Yes, it doesn't affect game parameters in any way, so it won't cause any desynchronization - it affects only the way screen is being shaken during rendering, so it is 100% client-side change.
