### ISSUE TITLE
UCS Hydra I has incorrectly placed weapon slot0.

### ISSUE THREAD

**Issue by nutzeeer** [InsideEarth2150/IEO-Updates#55]
**Describe the bug**
Incorrect weapon placement. (excact center of ship)

**To Reproduce**
Produce hydra I with weapons. second slot is in the ship center instead of the front.

**Expected behavior**
should be at the front

Screenshot:
![image](https://user-images.githubusercontent.com/81938977/120723900-f656ec00-c4d2-11eb-8362-3912422a26ff.png)
Also the grenade launcher has a nice range :)
![image](https://user-images.githubusercontent.com/81938977/120726037-8434d600-c4d7-11eb-9fef-dee71d8f2cd9.png)
better image

**Game (please complete the following information):**
 - Game: [e.g. The Moon Project]
 - Version [e.g. 2.2.0.9]

**Comment by GvardianDLVII** [comment]
Fixed in 2.2.1.2 (aka 2.2.1.1B Alpha)
