### ISSUE TITLE
Units equipped with the repair tool can repair, but they only use the repair script and cant attack

### ISSUE THREAD

**Issue by nutzeeer** [InsideEarth2150/IEO-Updates#60]
**Describe the bug**
Ships equipped with the repair tool can repair, but they use the repair script and cant attack. This is probably also true for the building take over think.

**To Reproduce**
Produce a ship that has a repair tool.

**Expected behavior**
Ships should use the ship script (or what ever is correct for ships) and not use the repair script when a repair tool is mounted. Though i dont know 

**Screenshots**
![image](https://user-images.githubusercontent.com/81938977/120725571-8cd8dc80-c4d6-11eb-865b-cce6606c2dd6.png)
the ships are not shooting.

**Game (please complete the following information):**
 - Game: [e.g. The Moon Project]
 - Version [e.g. 2.2.0.9]

**Comment by koniecpolski** [comment]
It is like that with ANY unit, that have mounted repair tool mounted in at least one light weapon slot. Not only ships.

**Comment by GvardianDLVII** [comment]
Fixed in 2.2.1.2 (aka 2.2.1.1B Alpha), at least partially. Due to different/separate unit classes, it is not possible to combine features of multiple unit types. The issue was fixed by disabling heavy weapon's sublsot for utilities specific to specialized classes (repair tools, building grabbers).
