### ISSUE TITLE
Enable the game to use a laptops dedicated GPU

### ISSUE THREAD

**Issue by nutzeeer** [InsideEarth2150/IEO-Updates#61]
**Is your feature request related to a problem? Please describe.**
My laptop has a Intel HD-520 integraded GPU and a nvidia 940MX GPU. The games setup program does not have a selection for the GPU and changing windows settings on which GPU should be used have no effect.

**Describe the solution you'd like**
Either make a selection possible, to save battery or get performance; Or make the dedicated GPU standard.

**Additional context**
I have tested the selection in the WW3 black gold game, which is the latest old style earth game, if i recall correctly. It also does not offer a selection.
Does Earth 2160 have this issue? Maybe a solution can be derived from it?

**Comment by GvardianDLVII** [comment]
I run the game on a laptop and the game is rendered by dedicated GPU. I think it is not something we can control from within the game or at least not easily. The NVIDIA control panel offer ways to select the preferred GPU for each process, though when it comes to the topic of GPU selection, codecs, alt-tabbing behaviour, capturing screen and all other issues regarding integration between the OS/hardware and the game, it all tends to be pretty random. I think it is not something that we can diagnose as game issue or fix. At least not for the moment.
