### ISSUE TITLE
Land button for scout unit

### ISSUE THREAD

**Issue by koniecpolski** [InsideEarth2150/IEO-Updates#62]
Supplier and any other air script unit lets player to land with it, but... Scouts use civilian unit script which doesn't have option for landing. It maybe isn't an issue for LC, but if someone would want to repair a damaged scout unit, he can't if it is still in the air. It has to land for the repairer.

**Comment by GvardianDLVII** [comment]
The issue will be addressed in the next version. All civilian air units will have basic regeneration and won't be able to land.
