### ISSUE TITLE
Let Gouger swim

### ISSUE THREAD

**Issue by koniecpolski** [InsideEarth2150/IEO-Updates#63]
LC's gouger unit is unable to move over the water, in contrast to every other unit belonging to LC. I guess devs were so busy thinking about the Moon (and forgetting that someone will construct that vehicle on Earth where actually water is), that they forgot to set a bit in _parameters_ file. 
It is **inconsistent** that gouger levitates above the surface of the ground (mines do not hit it) and it still can't follow the rest of LC troops through water.

Hopefully you could fix that since you have access to game parameters :D

**Comment by GvardianDLVII** [comment]
The feature will be present in the next version.
