### ISSUE TITLE
Game crashes in Constructor (F1) on 16:9 and wider resolutions

### ISSUE THREAD

**Issue by GvardianDLVII** [InsideEarth2150/IEO-Updates#9]
**Describe the bug**
As in the title. We already have the fix implemented, but we could try to integrate it into the patch, so that there is no need to apply it manually.

**To Reproduce**
1. Set resolution to 16:9
2. Start any game
3. Press F1

**Expected behavior**

**Screenshots**

**Videos**
If applicable, add videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - OS Edition: [e.g. Home/Pro]
 - OS Version: [e.g. 20H2]

**Game (please complete the following information):**
 - Game: [e.g. The Moon Project]
 - Version [e.g. 2.2]

**Additional context**

**Comment by AlphaOmega2020** [comment]
we will want to incorporate this and the titlebar fix into the updated exe.

**Comment by GvardianDLVII** [comment]
Fixed in extension library (EarthTmpExtensions) for TMP 2.2:
https://github.com/GvardianDLVII/EarthExtensions
